import { defineCatalog } from "@json-render/core";
import { schema } from "@json-render/react/schema";
import { z } from "zod";

/**
 * json-render + AI SDK Example Catalog
 *
 * Components for rendering data dashboards generated by the ToolLoopAgent.
 * Data flows in through tools (weather, GitHub, crypto, HN), not user actions.
 */
export const explorerCatalog = defineCatalog(schema, {
  components: {
    // Layout
    Stack: {
      props: z.object({
        direction: z.enum(["horizontal", "vertical"]).nullable(),
        gap: z.enum(["sm", "md", "lg"]).nullable(),
        wrap: z.boolean().nullable(),
      }),
      slots: ["default"],
      description: "Flex layout container",
      example: { direction: "vertical", gap: "md", wrap: null },
    },

    Card: {
      props: z.object({
        title: z.string().nullable(),
        description: z.string().nullable(),
      }),
      slots: ["default"],
      description: "Card container with optional title and description",
      example: { title: "Weather", description: "Current conditions" },
    },

    Grid: {
      props: z.object({
        columns: z.enum(["1", "2", "3", "4"]).nullable(),
        gap: z.enum(["sm", "md", "lg"]).nullable(),
      }),
      slots: ["default"],
      description: "Responsive grid layout container",
      example: { columns: "3", gap: "md" },
    },

    // Typography
    Heading: {
      props: z.object({
        text: z.string(),
        level: z.enum(["h1", "h2", "h3", "h4"]).nullable(),
      }),
      description: "Section heading",
      example: { text: "Data Explorer", level: "h1" },
    },

    Text: {
      props: z.object({
        content: z.string(),
        muted: z.boolean().nullable(),
      }),
      description: "Text content",
      example: { content: "Here is your data overview." },
    },

    // Data display
    Badge: {
      props: z.object({
        text: z.string(),
        variant: z
          .enum(["default", "secondary", "destructive", "outline"])
          .nullable(),
      }),
      description: "Status badge",
      example: { text: "Live", variant: "default" },
    },

    Alert: {
      props: z.object({
        variant: z.enum(["default", "destructive"]).nullable(),
        title: z.string(),
        description: z.string().nullable(),
      }),
      description: "Alert or info message",
    },

    Separator: {
      props: z.object({}),
      description: "Visual divider",
    },

    Metric: {
      props: z.object({
        label: z.string(),
        value: z.string(),
        detail: z.string().nullable(),
        trend: z.enum(["up", "down", "neutral"]).nullable(),
      }),
      description:
        "Single metric display with label, value, and optional trend indicator",
      example: {
        label: "Temperature",
        value: "72F",
        detail: "Feels like 68F",
        trend: "up",
      },
    },

    Table: {
      props: z.object({
        statePath: z.string(),
        columns: z.array(
          z.object({
            key: z.string(),
            label: z.string(),
          }),
        ),
        emptyMessage: z.string().nullable(),
      }),
      description:
        "Data table. statePath points to an array of objects in state.",
      example: {
        statePath: "/stories",
        columns: [
          { key: "title", label: "Title" },
          { key: "score", label: "Score" },
        ],
      },
    },

    Link: {
      props: z.object({
        text: z.string(),
        href: z.string(),
      }),
      description: "External link that opens in a new tab",
      example: { text: "View on GitHub", href: "https://github.com" },
    },

    // Charts
    BarChart: {
      props: z.object({
        title: z.string().nullable(),
        statePath: z.string(),
        xKey: z.string(),
        yKey: z.string(),
        aggregate: z.enum(["sum", "count", "avg"]).nullable(),
        color: z.string().nullable(),
        height: z.number().nullable(),
      }),
      description:
        "Bar chart visualization. statePath points to an array of objects. xKey is the category field, yKey is the numeric value field.",
    },

    LineChart: {
      props: z.object({
        title: z.string().nullable(),
        statePath: z.string(),
        xKey: z.string(),
        yKey: z.string(),
        aggregate: z.enum(["sum", "count", "avg"]).nullable(),
        color: z.string().nullable(),
        height: z.number().nullable(),
      }),
      description:
        "Line chart visualization. statePath points to an array of objects. xKey is the x-axis field, yKey is the numeric value field.",
    },

    // Interactive
    Tabs: {
      props: z.object({
        defaultValue: z.string().nullable(),
        tabs: z.array(
          z.object({
            value: z.string(),
            label: z.string(),
          }),
        ),
      }),
      slots: ["default"],
      description: "Tabbed content container",
    },

    TabContent: {
      props: z.object({
        value: z.string(),
      }),
      slots: ["default"],
      description: "Content for a specific tab",
    },

    Progress: {
      props: z.object({
        value: z.number(),
        max: z.number().nullable(),
      }),
      description: "Progress bar",
    },

    Skeleton: {
      props: z.object({
        width: z.string().nullable(),
        height: z.string().nullable(),
      }),
      description: "Loading placeholder",
    },
  },

  actions: {},
});
